### PR TITLE
fix building issue introduced by https://github.com/ClickHouse-Extras…

### PR DESCRIPTION
**Pull request by taiyang-li**
fix building issue introduced by https://github.com/ClickHouse-Extras/arrow/pull/9

### CODE REVIEW

**Comment by taiyang-li** [comment]
@Avogar  Can you review this pr?  Thank you in advance.

**Comment by Avogar** [comment]
I don't have access to merge this PR(

**Comment by Avogar** [comment]
Now I can merge it

**Review by Avogar — APPROVED** [review]

**Comment by taiyang-li** [comment]
@Avogar Thank you very much !

**Pull request merged**
